typography_spectrum: 0.8065444712992758
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9952739235013723
  lightness: 0.7894811755977571
  saturation: 0.34481128491461277
  rhythmicContrast: 0.8027304979041219
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7277355547994375
analytics:
  google: null
  facebook: null
  twitter: null
name: WTF is this
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This is awesome
purpose: []
